site_name: "compilerla/template-devcontainer: Documentation"
repo_url: https://github.com/compilerla/template-devcontainer
edit_uri: edit/main/docs
site_url: https://compilerla.github.io/template-devcontainer

theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  analytics:
    provider: google
    property: G-xxxxxxxxxx

plugins:
  - search
  - awesome-pages
  - redirects:
      redirect_maps:

extra_css:
  - https://use.fontawesome.com/releases/v6.1.2/css/all.css

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - mdx_truly_sane_lists
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty
