name: compilerla/template-devcontainer

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    entrypoint: []
    command: sleep infinity
    image: compilerla/template-devcontainer:dev
    volumes:
      - ../:/home/compiler/src
