name: Publish docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/mkdocs.yml"
      - "docs/**"
      - ".markdownlint.yaml"
      - "mkdocs.yml"

jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          REQUIREMENTS: docs/requirements.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
